- name: Disable modules
  lineinfile:
    dest: /etc/modprobe.d/CIS.conf
    state: present
    create: yes
    line: "{{ item }}"
  loop:
    - "install dccp /bin/true"
    - "install sctp /bin/true"
    - "install rds /bin/true"
    - "install tipc /bin/true"
    - "install cramfs /bin/true"
    - "install freevxfs /bin/true"
    - "install hfs /bin/true"
    - "install hfsplus /bin/true"
    - "install jffs2 /bin/true"
    - "install squashfs /bin/true"
    - "install udf /bin/true"
