
---
# tasks file for mariadb
- name: Install the latest version of MariaDB
  package:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest

- name: mysql config
  ansible.builtin.template:
    src: templates/mariadb-server.cnf
    dest: /etc/mysql/mariadb.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: '0644'

- name: Touch the log file
  ansible.builtin.file:
    path: /var/log/mysql/mysql.log
    state: touch
    owner: mysql
    group: mysql
    mode: '0660'

- name: Start service MariaDB, if not started
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: Create database user
  community.mysql.mysql_user:
    name: div_db
    password: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
